#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : lsacpi
Version  : 6
Release  : 14
URL      : http://localhost/cgit/projects/lsacpi/snapshot/lsacpi-6.tar.xz
Source0  : http://localhost/cgit/projects/lsacpi/snapshot/lsacpi-6.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: lsacpi-bin = %{version}-%{release}
Requires: lsacpi-data = %{version}-%{release}

%description
No detailed description available

%package bin
Summary: bin components for the lsacpi package.
Group: Binaries
Requires: lsacpi-data = %{version}-%{release}

%description bin
bin components for the lsacpi package.


%package data
Summary: data components for the lsacpi package.
Group: Data

%description data
data components for the lsacpi package.


%prep
%setup -q -n lsacpi-6
cd %{_builddir}/lsacpi-6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604102052
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1604102052
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/lsacpi

%files data
%defattr(-,root,root,-)
/usr/share/misc/acpi.ids
