#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : lsacpi
Version  : 5
Release  : 10
URL      : http://localhost/cgit/projects/lsacpi/snapshot/lsacpi-5.tar.bz2
Source0  : http://localhost/cgit/projects/lsacpi/snapshot/lsacpi-5.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: lsacpi-bin
Requires: lsacpi-data

%description
No detailed description available

%package bin
Summary: bin components for the lsacpi package.
Group: Binaries
Requires: lsacpi-data

%description bin
bin components for the lsacpi package.


%package data
Summary: data components for the lsacpi package.
Group: Data

%description data
data components for the lsacpi package.


%prep
%setup -q -n lsacpi-5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1510693303
make V=1  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1510693303
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/lsacpi

%files data
%defattr(-,root,root,-)
/usr/share/misc/acpi.ids
